cleanup admin dashboard mvc #18132
telerik/admin-dashboard-sample-app-mvc pull request #21
Opened 2023-06-20 12:04 UTC by antonmironovv

2023-06-21 07:31 UTC, antonmironovv commented
telerik/kendo#18132

2023-06-30 08:30 UTC, VicTachev approved these changes

2023-08-11 12:32 UTC, VicTachev approved these changes

2023-09-20 13:18 UTC, Dimitar-Goshev requested changes
Project fails to build. Multiple unnecessary references added.

2023-09-20 13:25 UTC, Dimitar-Goshev approved these changes
I fixed the issues with https://github.com/telerik/admin-dashboard-sample-app-mvc/pull/21/commits/55c1c7916371c6bdb4260cf3bf3f04b985a1f0e1

2023-09-20 13:25 UTC, merged